import productDescriptionsImage from '@/assets/Product descriptions.png';
import ecomSeoFrameworkImage from '@/assets/E-com SEO framework.png';
import translateVideoImage from '@/assets/translate video.png';
import n8nEmailImage from '@/assets/n8n-email-automation.png';
import n8nWhatsAppImage from '@/assets/n8n-whatsapp-chatbot.png';
import apiGuideWhatsAppImage from '@/assets/API guide whatsapp.webp';
import n8nOpenRouterImage from '@/assets/n8n open router.webp';
import klaviyoImage from '@/assets/klaviyo.png';
import apifyVideoImage from '@/assets/Apify video.jpg';
import shopifyTranslateAiImage from '@/assets/SCR-20250806-pnlp.png';
import gscAutoIndexerImage from '@/assets/indexing.png';
import credentialsImage from '@/assets/credentials.jpeg';
import googleTrendsImage from '@/assets/maxresdefault.jpg';

export const youtubePosts = [
  {
    id: 15,
    slug: 'permanent-shopify-admin-api-key',
    title: 'Get a Permanent Shopify Admin API Key',
    excerpt: 'Create a Shopify app, capture the OAuth code and exchange it for a long-lived Admin API access token.',
    publishDate: '2026-01-21',
    readTime: '10 min read',
    category: 'Shopify API',
    thumbnail: '/shopify-api-integraties.jpeg',
    videoId: 'kDXRcev9d34',
    tags: ['Shopify', 'Admin API', 'OAuth'],
  },
  {
    id: 14,
    slug: 'automated-google-trends-scanner-to-find-winning-niches',
    title: 'Automated Google Trends Scanner',
    excerpt: 'Build an automated AI system that scans Google Trends and identifies profitable e-commerce opportunities.',
    publishDate: '2025-08-28',
    readTime: '22 min read',
    category: 'Business Automation',
    thumbnail: googleTrendsImage,
    videoId: '7Zesux97FyI',
    tags: ['Google Trends', 'N8N', 'AI'],
  },
  {
    id: 13,
    slug: 'automate-shopify-multi-language-for-free-no-translation-apps',
    title: 'Automate Shopify Multi Language for Free',
    excerpt: 'Automate multi-language support for Shopify without expensive translation apps.',
    publishDate: '2025-08-23',
    readTime: '25 min read',
    category: 'Shopify Automation',
    thumbnail: shopifyTranslateAiImage,
    videoId: 'n34TNM1Gu6o',
    tags: ['Shopify', 'Translation', 'Automation'],
  },
  {
    id: 12,
    slug: 'google-api-credentials-setup',
    title: 'Set Up Google API Credentials for N8N',
    excerpt: 'Set up Google Cloud, OAuth, consent screens and N8N credentials for reliable API automation.',
    publishDate: '2025-08-10',
    readTime: '18 min read',
    category: 'API Setup',
    thumbnail: credentialsImage,
    videoId: '8HtX1jUnKKk',
    tags: ['Google API', 'OAuth', 'N8N'],
  },
  {
    id: 11,
    slug: 'google-search-console-auto-indexer',
    title: 'Automate Google Search Console Indexing',
    excerpt: 'Build an automated indexing workflow for Google Search Console using N8N.',
    publishDate: '2025-08-10',
    readTime: '25 min read',
    category: 'SEO Automation',
    thumbnail: gscAutoIndexerImage,
    videoId: 'rDOCbrQtTp8',
    tags: ['SEO', 'Indexing', 'N8N'],
  },
  {
    id: 10,
    slug: 'translate-your-shopify-store-automatically-with-ai-n8n-google-sheets',
    title: 'Translate Your Shopify Store Automatically',
    excerpt: 'Use AI, N8N and Google Sheets to translate Shopify content without manual work.',
    publishDate: '2025-08-06',
    readTime: '22 min read',
    category: 'Shopify Automation',
    thumbnail: shopifyTranslateAiImage,
    videoId: 'x913ZsKXpSA',
    tags: ['Shopify', 'AI', 'Google Sheets'],
  },
  {
    id: 9,
    slug: 'automated-lead-scraping-with-apify-and-n8n-google-maps-to-sheets',
    title: 'Automated Lead Scraping with Apify and N8N',
    excerpt: 'Scrape leads from Google Maps, enrich them with AI and store them in Google Sheets.',
    publishDate: '2025-07-29',
    readTime: '15 min read',
    category: 'Lead Generation',
    thumbnail: apifyVideoImage,
    videoId: 'fWoMKTx9X38',
    tags: ['Apify', 'Lead Generation', 'N8N'],
  },
  {
    id: 8,
    slug: 'klaviyo-signup-forms-email-automation-send-deliverables-instantly',
    title: 'Klaviyo Signup Forms and Email Automation',
    excerpt: 'Set up Klaviyo signup forms and automate instant delivery of lead magnets.',
    publishDate: '2025-07-27',
    readTime: '12 min read',
    category: 'Email Marketing',
    thumbnail: klaviyoImage,
    videoId: 'QV6Xt8f8d2w',
    tags: ['Klaviyo', 'Email', 'Automation'],
  },
  {
    id: 7,
    slug: 'build-your-own-whatsapp-chatbot-with-n8n-no-code-guide',
    title: 'Build a WhatsApp AI Agent in N8N',
    excerpt: 'Create an AI-powered WhatsApp agent with N8N and WhatsApp Business API workflows.',
    publishDate: '2025-07-28',
    readTime: '25 min read',
    category: 'Chatbot Automation',
    thumbnail: n8nWhatsAppImage,
    videoId: 'iMs_vGYUq8w',
    tags: ['WhatsApp', 'AI Agent', 'N8N'],
  },
  {
    id: 6,
    slug: 'how-to-connect-open-router-to-n8n',
    title: 'Connect OpenRouter to N8N',
    excerpt: 'Connect OpenRouter API to N8N for AI-powered workflows and unified model access.',
    publishDate: '2025-07-28',
    readTime: '15 min read',
    category: 'AI Integration',
    thumbnail: n8nOpenRouterImage,
    videoId: 'OPENROUTER_VIDEO_ID',
    tags: ['OpenRouter', 'AI', 'N8N'],
  },
  {
    id: 5,
    slug: 'how-to-connect-whatsapp-business-cloud-credentials-to-n8n',
    title: 'Connect WhatsApp Business Cloud to N8N',
    excerpt: 'Set up WhatsApp Business Cloud credentials, webhooks and message automation in N8N.',
    publishDate: '2025-07-28',
    readTime: '20 min read',
    category: 'WhatsApp Integration',
    thumbnail: apiGuideWhatsAppImage,
    videoId: 'WHATSAPP_VIDEO_ID',
    tags: ['WhatsApp', 'Meta', 'N8N'],
  },
  {
    id: 4,
    slug: 'cold-email-automation-in-n8n-step-by-step-with-free-template',
    title: 'Cold Email Automation in N8N',
    excerpt: 'Build a repeatable cold email workflow with Google Sheets, rotating templates, personalization and send logging.',
    publishDate: '2025-01-25',
    readTime: '20 min read',
    category: 'Email Automation',
    thumbnail: n8nEmailImage,
    videoId: '4k7Zd4A0WzQ',
    tags: ['N8N', 'Cold Email', 'Google Sheets'],
  },
  {
    id: 3,
    slug: 'how-to-write-product-descriptions-that-rank-on-google',
    title: 'Write Product Descriptions That Rank on Google',
    excerpt: 'Use a practical framework to write product descriptions that rank and convert.',
    publishDate: '2025-01-20',
    readTime: '12 min read',
    category: 'E-commerce SEO',
    thumbnail: productDescriptionsImage,
    videoId: 'k2-w1UWjBEU',
    tags: ['SEO', 'E-commerce', 'Copywriting'],
  },
  {
    id: 2,
    slug: 'real-ecommerce-seo-my-framework-for-long-term-organic-growth',
    title: 'Real Ecommerce SEO Framework',
    excerpt: 'A long-term organic growth framework for scaling e-commerce stores with SEO.',
    publishDate: '2025-01-15',
    readTime: '18 min read',
    category: 'E-commerce SEO',
    thumbnail: ecomSeoFrameworkImage,
    videoId: '7cshITRgi10',
    tags: ['SEO', 'E-commerce', 'Growth'],
  },
  {
    id: 1,
    slug: 'shopify-translate-and-adapt-add-unlimited-languages-bulk-translation-hack',
    title: 'Shopify Translate and Adapt Bulk Translation Hack',
    excerpt: 'Add languages to Shopify with Translate and Adapt plus a faster bulk translation workflow.',
    publishDate: '2025-01-10',
    readTime: '15 min read',
    category: 'Shopify Tutorial',
    thumbnail: translateVideoImage,
    videoId: '1bWKz69cBIU',
    tags: ['Shopify', 'Translation', 'International SEO'],
  },
];

export function getYouTubePost(slug) {
  return youtubePosts.find((post) => post.slug === slug);
}

export function getSortedYouTubePosts() {
  return [...youtubePosts].sort((a, b) => new Date(b.publishDate) - new Date(a.publishDate));
}
